name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean install
    - name: Test with Maven and Jacoco
      run: mvn -B clean test jacoco:report
    - name: Check code coverage
      run: |
        coverage=$(grep -oP '(?<=<lineRate>)\d+\.\d+' target/site/jacoco/jacoco.xml)
        if [ $(echo "$coverage < 0.8" | bc -l) -eq 1 ]; then
          echo "Code coverage is below 80% (actual: $coverage%)"
          exit 1
        fi
