name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
      
    - name: Check code coverage
      run: mvn jacoco:report
      
    - name: Upload code coverage report
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: target/site/jacoco/index.html
        
    - name: Check coverage threshold
      run: |
        coverage=$(grep -oP "(?<=Overall coverage:).*" target/site/jacoco/index.html | awk '{print $1}')
        echo "Coverage is set to $coverage"
        coverage=${coverage%\%}
        if [ $coverage -lt 80 ]; then
          echo "Coverage is below 80%"
          exit 1
        fi
        echo "Coverage is above 80%"
